version: '3'
services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '4000:81'
      - '443:443'
    environment:
      - DB_MYSQL_HOST=db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=nginx
      - DB_MYSQL_PASSWORD=nginxsecurepass
      - DB_MYSQL_HOST=nginx
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=nginxsecurepass
      - MYSQL_ROOT_DATABASE=nginx
      - MYSQL_ROOT_USER=nginx
      - MYSQL_PASSWORD=nginxsecurepass
    volumes:
      - ./data/mysql:/var/lib/mysql